#!/usr/bin/env python3
# Run an object file and output an instruction trace
# Usage: smite-trace OBJECT-FILE TRACE-FILE

import sys
from ctypes import *
from ctypes.util import find_library

libsmite = CDLL(find_library("smite"))
word_size = c_int.in_dll(libsmite, "smite_word_size")

S = libsmite.smite_init_default_stacks(0x100000)
h = open(sys.argv[1], "rb")
libsmite.smite_load_object(S, h.fileno(), 0)
h.close()

h = open(sys.argv[2], "w")

while True:
    ret = libsmite.smite_single_step(S)
    if ret != -258:
        break
    print(libsmite.smite_get_ITYPE(S), libsmite.smite_get_I(S), file=h)
