version: "{build}"
clone_folder: c:\projects\smite

# FIXME: currently does not work with IPython: get error "stdin is not a tty"
# when trying to test version of IPython in configure

environment:
  global:
    VERBOSE: 1 # Get test logs in output
  matrix:
    - MSYSTEM: MSYS
    - MSYSTEM: MINGW64
    - MSYSTEM: MINGW32

init:
  - git config --global core.autocrlf input

install:
  - C:\msys64\usr\bin\bash.exe -lc "cd c:/projects/smite && ./build-aux/appveyor-install.sh"

build_script:
  - C:\msys64\usr\bin\bash.exe -lc "cd c:/projects/smite && ./bootstrap && ./configure --enable-silent-rules && make && make install && make check"
