#!/usr/bin/python3
# Generate the specializer's trace file.
#
# Copyright (c) 2019 Mit authors
#
# The package is distributed under the MIT/X11 License.
#
# THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
# RISK.

import sys, pickle, hashlib, gzip

from mit import *

if len(sys.argv) < 3:
    print("Usage: gen-trace TRACE-FILE PFORTH-ARGUMENT...", file=sys.stderr)
    sys.exit(1)
trace_filename = sys.argv[1]
pforth_arguments = sys.argv[2:]

# Generate the trace by building pforth
VM = State()
VM.load('pforth-base')
with open(trace_filename, 'wb') as trace_file:
    VM.run(pforth_arguments, trace_file=trace_file)
