#!/usr/bin/env python3
#
# (c) 2018-2019 Mit authors
#
# The package is distributed under the MIT/X11 License.
#
# THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
# RISK.

import argparse, json

from mit_core.vm_data import Instruction


# Command-line arguments
parser = argparse.ArgumentParser(
    prog='gen-minimal-profile',
    description='Generate the smallest useful mit-profile.json file.',
)
args = parser.parse_args()

# Generate a label to guess each instruction.
# If an Instruction is never guessed, it will not be present in any future
# profile either.
states = []
next = -1
for (state, instruction) in reversed(list(enumerate(Instruction))):
    states.append((instruction, next))
    next = state
states.reverse()

# Generate the file.
print(json.dumps([
    {
        "path": "",
        "guess": instruction.name,
        "correct_state": 0,
        "wrong_state": wrong_state,
        "correct_count": 1,
        "wrong_count": (len(states) - 1) - state,
    }
    for state, (instruction, wrong_state) in enumerate(states)
]))