#!/usr/bin/env python3
# Generate code for instructions.
#
# (c) Mit authors 1994-2019
#
# The package is distributed under the MIT/X11 License.
#
# THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
# RISK.

import sys, pickle, textwrap

from mit_core.code_util import Code
from mit_core.vm_data import Instruction
from mit_core.params import opcode_bit
from specializer import CacheState, gen_case
from path import SpecializedInstruction, State


# Load the labels file, which tells us what control-flow graph to generate.
if len(sys.argv) != 2:
    print("Usage: gen-specializer LABELS-FILE", file=sys.stderr)
    sys.exit(1)

class Label:
    '''
     - index - int - the index of this Label.
     - name - str - The C identifier of this Label.
     - tos_constant - int - the constant at the top of the stack at this
       Label, or `None` if the top stack item is not known to be constant.
     - cached_depth - int - the number of stack items that are cached in C
       variables at this Label.
     - checked_depth - int - the number of empty stack slots that are known to
       exist above the top of the stack at this Label.
     - path - str - the instruction sequence just executed.
     - guess - str - the most probable next instruction sequence.
       (space-separated).
     - if_correct - int - the Label index to jump to if `guess` is correct.
     - if_wrong - int - the Label index to jump to if `guess` is wrong.
    '''
    def __init__(
        self,
        index,
        name,
        tos_constant=None,
        cached_depth=0,
        checked_depth=0,
        path=None,
        guess=None,
        if_correct=None,
        if_wrong=None,
    ):
        self.index = index
        self.name = name
        self.tos_constant = tos_constant
        self.cached_depth = cached_depth
        self.checked_depth = checked_depth
        self.path = path
        self.guess = guess
        self.if_correct = if_correct
        self.if_wrong = if_wrong

    def cache_state(self):
        '''Returns a fresh CacheState describing this Label.'''
        return CacheState(self.cached_depth, self.checked_depth)

    def goto(self, cache_state):
        '''
        Returns a Code to jump to this Label.
         - cache_state - The CacheState before the goto. This method generates
           code to flush the cache to meet the expectations at this Label.
        '''
        code = Code()
        code.extend(cache_state.flush(self.cache_state()))
        code.append('goto {};'.format(self.name))
        return code

    def generate_code(self, profiling=False):
        '''
        Returns a Code to place at this Label.
        Also returns the peak value of `CacheState.cached_depth`.
        '''
        # Generate the Code for the branch where the guess is correct.
        # Also, compute the guess bit string.
        c_code = Code()
        if profiling:
            c_code.append('state_guess_correct[{}]++;'.format(self.index))
        opcode_value = 0 # Bit pattern to match.
        opcode_bits = 0 # Number of bits to match.
        state = State(tos_constant=self.tos_constant)
        cache_state = self.cache_state()
        for i_name in self.guess.split():
            instruction = state.specialize_instruction(Instruction[i_name])
            assert opcode_bits is not None
            opcode_value |= instruction.opcode << opcode_bits
            opcode_bits += opcode_bit
            if instruction.terminal:
                opcode_bits = None # Must match all bits.
            state = state.step(instruction)
            c_code.extend(Code('''\
                initial_pc = S->pc;
                initial_ir = S->ir;
                S->ir >>= MIT_OPCODE_BIT;''',
                '{{ // {}'.format(instruction.name),
                    gen_case(instruction, cache_state),
                '}',
            ))
        c_code.extend(label_by_index(self.if_correct).goto(cache_state))
        pops = -state.stack_min
        pushes = state.stack_max - state.stack_min
        max_cached_depth = (
            max(self.cached_depth, -state.stack_min) + state.stack_max)
        # Generate the code for the branch where the guess is wrong.
        w_code = Code()
        if profiling:
            w_code.append('state_guess_wrong[{}]++;'.format(self.index))
        cache_state = self.cache_state()
        w_code.extend(label_by_index(self.if_wrong).goto(cache_state))
        # Generate the guess condition.
        opcode = 'S->ir'
        if opcode_bits is not None:
            opcode = '({} & {})'.format(opcode, hex((1 << opcode_bits) - 1))
        cache_state = self.cache_state()
        tests = [
            '{} == {}'.format(opcode, hex(opcode_value)),
            'likely({})'.format(cache_state.underflow_test(pops)),
            'likely({})'.format(cache_state.overflow_test(pops, pushes)),
        ]
        # Generate the main Code.
        code = Code(
            '// History: {}'.format(self.path),
            'assert(error == MIT_ERROR_OK);',
            'assert(cached_depth == {});'.format(self.cached_depth),
            'if ({}) {{'.format(' && '.join(tests)),
            c_code,
            '}',
        )
        code.extend(w_code)
        return (code, max_cached_depth)


with open(sys.argv[1], "rb") as h:
    labels = [
        Label(index, 'A_{}'.format(index), tos, ca, ch, path, gu, ic, iw)
        for index, (tos, ca, ch, path, gu, ic, iw) in enumerate(pickle.load(h))
    ]

def label_by_index(index):
    if index is None:
        return Label(len(labels), 'A_FALLBACK')
    return labels[index]


def gen_labels_code(profiling=False):
    code = Code()
    code.append(Code('''\
        mit_uword initial_pc, initial_ir;
        // The number of stack items cached in C variables.
        int cached_depth = 0;
        goto A_0;

        // Each A_XXX label has an expectation of what instruction sequence
        // probably comes next. If correct, there is a fast path for executing
        // that sequence, otherwise we fall back on a slow path with broader
        // expectations. Ultimately, we fall back to `A_FALLBACK` which calls
        // `mit_single_step()` to handle corner cases.
        //
        // The calling convention at each A_XXX label is as follows:
        //
        //  - On entry, `error` is `MIT_ERROR_OK`. `cached_depth` is a
        //    compile-time constant indicating how many top stack items are in
        //    C variables.
        //  - Before running the `Instruction.code` for an instruction, record
        //    `initial_pc` and `initial_ir`, and right-shift `ir`.
        //  - When an error occurs, call `RAISE(code)`.
        //    It sets `error` to the return code; then it resets pc and
        //    ir to their initial values, and does "goto error".
        //  - On exit, whether by `RAISE` or otherwise, all Mit
        //    registers must be set according to the Mit spec. In particular,
        //    there must be no side effects before a RAISE, except on `ir` and
        //    `pc`, which will be reset as described above.
    '''))
    max_cached_depth = 0
    for label in labels:
        code.append('')
        code.append('{label_name}:'.format(label_name=label.name))
        label_code, cached_depth = label.generate_code(profiling)
        code.append(label_code)
        max_cached_depth = max(max_cached_depth, cached_depth)
    code.append('')
    code.append('''\
        A_FALLBACK:
            assert(error == MIT_ERROR_OK);
            assert(cached_depth == 0);
            *real_S = state;
            error = mit_single_step(real_S);
            state = *real_S;
            continue;

        error:
            S->pc = initial_pc;
            S->ir = initial_ir;
            switch (cached_depth) {
    ''')
    switch_code = Code()
    cache_state = CacheState(max_cached_depth, 0)
    while cache_state.cached_depth > 0:
        switch_code.append('case {}:'.format(cache_state.cached_depth))
        case_code = Code()
        case_code.extend(cache_state.flush(cache_state.cached_depth - 1))
        case_code.append('// Falls through.')
        switch_code.append(case_code)
    switch_code.append('''\
        case 0:
            break;
        default:
            assert(0); // Unreachable.
        }
    ''')
    code.append(switch_code)

    return code, max_cached_depth

# Generate the code for the labels first, so as to compute `max_cached_depth`.
labels_code, max_cached_depth = gen_labels_code(profiling=False)
labels_code_profiling = gen_labels_code(profiling=True)

def gen_body_code(profiling=False):
    code = Code()
    code.append('''\
        mit_state state = *real_S;
        mit_state *const S = &state;
        int error = MIT_ERROR_OK;
    ''')
    if max_cached_depth > 0:
        cache_state = CacheState(max_cached_depth, 0)
        code.append('mit_word {};'.format(
            ', '.join(
                cache_state.var(pos)
                for pos in reversed(range(max_cached_depth))
            )
        ))
    code.append('do {')
    code.extend(labels_code)
    code.append('''\
        } while (error == MIT_ERROR_OK);
        *real_S = state;
        return error;
    ''')

    return code

# Construct a Code for the function body, copying `labels_code`.
body_code = gen_body_code(profiling=False)
body_code_profiling = gen_body_code(profiling=True)


# Generate the code for the entire source file.
code = Code()
code.append('''\
    // Auto-generated by gen-specializer - DO NOT EDIT.
    // Run the virtual machine.

    #include "config.h"

    #include <assert.h>
    #include <stdio.h>
    #include <unistd.h>

    #include "mit/mit.h"
    #include "mit/features.h"

    #include "run.h"


    #define NUM_LABELS {num_labels}
    // The number of times we guessed correctly at each specializer label.
    static unsigned long long state_guess_correct[NUM_LABELS];
    // The number of times we guessed wrong at each specializer label.
    static unsigned long long state_guess_wrong[NUM_LABELS];

    void mit_profile_init(void)
    {{
        for (unsigned i = 0; i < NUM_LABELS; i++)
            state_guess_correct[i] = state_guess_wrong[i] = 0;
    }}

    int mit_profile_dump(int fd)
    {{
        // Open output stream (for buffering)
        int dup_fd = dup(fd);
        if (dup_fd == -1)
            return -1;
        FILE *fp = fdopen(dup_fd, "w");
        if (fp == NULL)
            return -1;
        else {{
            if (fprintf(fp, "[") < 0)
                goto err;
            const char *sep = "";
            for (unsigned i = 0; i < NUM_LABELS; i++) {{
                if (fprintf(fp, "%s\\n  {{\\"c\\": %llu, \\"w\\": %llu}}",
                            sep, state_guess_correct[i], state_guess_wrong[i])
                    < 0)
                    goto err;
                sep = ",";
            }}
            if (fprintf(fp, "\\n]\\n") < 0)
                goto err;
            if (fclose(fp) == 0)
                return 0;
        }}
    err:
        return -1;
    }}

    mit_word mit_specializer_run(mit_state * restrict real_S) {{
'''.format(num_labels=len(labels)))
code.append(body_code)
code.append('''\
    }

    mit_word mit_profile_run(mit_state * restrict real_S) {
''')
code.append(body_code_profiling)
code.append('}')

print(code)