#!/usr/bin/python3
# Generate the predictor file.
#
# Copyright (c) 2019 Mit authors
#
# The package is distributed under the MIT/X11 License.
#
# THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
# RISK.

import sys

from mit import *


if len(sys.argv) < 3:
    print("Usage: gen-predictor PREDICTOR-FILENAME PFORTH-ARGUMENT...", file=sys.stderr)
    sys.exit(1)
predictor_filename = sys.argv[1]
pforth_arguments = sys.argv[2:]

# Generate the predictor
VM = State()
VM.load('pforth-base')
libmitfeatures.mit_predictor_init()
VM.run(pforth_arguments, predictor=True)
with open(predictor_filename, 'w') as predictor_file:
    libmitfeatures.mit_predictor_dump(predictor_file.fileno())
