#!/bin/sh
# Find symbols that are exported from the main library
# FIXME: Make this portable; currently works only with GNU tools nm & rev

PACKAGE=$1
SRCDIR=$2

make >&2

(
    # Find exported symbols
    nm --defined-only .libs/*.o | cut -d " " -f 2-3 | grep ^[A-Zuvw] | cut -d " " -f 2 | grep -v "\\." | sed -e "s/^${PACKAGE}_//"

    # Get internal headers that correspond to public headers
    HEADERS=`grep "^internal_HDRS = " "$SRCDIR/Makefile.am" | cut -d " " -f 3-`

    # Find typedefs
    # Simple typedefs
    grep "^typedef.*[[:alpha:]];$" $HEADERS | rev | cut -d ";" -f 2 | cut -d " " -f 1 | rev
    # Function pointer typedefs
    grep "^typedef.*(\*[[:alnum:]_]\+)" $HEADERS | rev | cut -d "(" -f 2 | tr -d ')*' | rev
) | sort -u # Sort for ease of diffing/debugging
