#!/usr/bin/env python3
# Generate trap code enums.
#
# (c) Mit authors 2018-2020
#
# The package is distributed under the MIT/X11 License.
#
# THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
# RISK.

from mit_core.code_util import Code, enum_to_python, copyright_banner
import mit_core.stack
mit_core.stack.TYPE_SIZE_UNKNOWN = 0

import traps


code = Code()
GENERATOR_PROGRAM = 'gen-trap-enums'
PURPOSE = 'Trap code enumerations.'
COPYRIGHT_YEARS = '2018-2019'

code = copyright_banner(GENERATOR_PROGRAM, PURPOSE, COPYRIGHT_YEARS, comment='#')

code.append('''
from enum import Enum, IntEnum, unique
from .autonumber import AutoNumber
''')
code.append('')
code.append('')

lib_code = Code(
    "'''",
    traps.LibInstruction.__doc__,
    "'''",
    '''\
        def __init__(self, library, opcode):
            self.library = library
            self.opcode = opcode

        def __int__(self):
            return self.opcode
    ''',
)
lib_code.append('')
for lib in traps.LibInstruction:
    lib_code.append('{} = ({}, {:#x})'.format(
        lib.name,
        lib.library.__name__,
        lib.opcode,
    ))
    code.extend(enum_to_python(lib.library, lambda i: "{:#x}".format(i.opcode)))
    code.append('')
code.append('''\
    @unique
    class LibInstruction(Enum):
''')
code.append(lib_code)

print(code)
