#!/usr/bin/env python3
# Run an object file and output an instruction trace
# (c) Reuben Thomas 2019
# Usage: smite-trace OBJECT-FILE TRACE-FILE

import sys

from smite import *
VM = State()
VM.globalize(globals())

if len(sys.argv) != 2:
    print("Usage: smite-trace OBJECT-FILE TRACE-FILE")
    sys.exit(1)
load(sys.argv[1])
h = open(sys.argv[2], "w")

while True:
    if step() != -257:
        break
    print(ITYPE.get(), I.get(), file=h)
