// Functions and macros used by instruction actions, referred to by code
// generated by gen-actions.
//
// (c) Reuben Thomas 1994-2019
//
// The package is distributed under the GNU Public License version 3, or,
// at your option, any later version.
//
// THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER‘S
// RISK.

#ifndef SMITE_ACTIONS_COMMON
#define SMITE_ACTIONS_COMMON


#include <string.h>


#define DIVZERO(x)                              \
    if (x == 0)                                 \
        RAISE(-8);

static void trace(smite_state *S, int type, smite_WORD opcode) {
    if (S->trace_fp)
        fprintf(S->trace_fp, "%d %"PRI_XWORD"\n", type, (smite_UWORD)opcode);
}


#endif
