#!/usr/bin/env python3
# Calculate type sizes for extra instructions.
#
# (c) SMite authors 2019
#
# The package is distributed under the MIT/X11 License.
#
# THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
# RISK.

import sys
import re
from pprint import pformat

from smite_core.vm_data_extra import *


# Read list of types
types = []
for line in open('type-sizes.ac').readlines():
    m = re.match(r"^AC_CHECK_SIZEOF\(\[(.*)\]\)", line)
    if m:
        types.append(m.group(1))

# Read sizes from stdin
sizes = [line.rstrip() for line in sys.stdin]

# Make output dict
assert len(types) == len(sizes)
type_size = {type: int(size) for (type, size) in zip(types, sizes)}

# Print output
print('type_sizes = ' + pformat(type_size))
