#!/usr/bin/env python3
# Calculate type sizes for extra instructions.
#
# (c) Reuben Thomas 2019
#
# The package is distributed under the MIT/X11 License.
#
# THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
# RISK.

import re

from smite_core.vm_data_extra import *


print('''\
AC_INIT([type-sizes], [0.1])
ac_includes_default="\\
{}"
'''.format(re.sub('"', '\\"', includes)))

for type in list(set([type for lib in LibActions
                      for type in lib.value.types()])):
    print('AC_CHECK_SIZEOF([{}])'.format(type))

# We don't need this header, but autoconf insists we define it.
print('AC_CONFIG_HEADERS([type-sizes.h])')
