#!/usr/bin/env python3

from instructions import Opcodes, actions

print('// Auto-generated by "gen-names.py" - DO NOT EDIT.\n')
for (instruction, opcode) in Opcodes.__members__.items():
    print('''\
    INSTRUCTION(%(instruction)s, 0x%(opcode)x)
''' % {
        'instruction': instruction,
        'opcode': opcode,
    }, end='')
