#!/usr/bin/env python3
# Generate instructions opcode list.
#
# (c) Mit authors 2018-2020
#
# The package is distributed under the MIT/X11 License.
#
# THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
# RISK.

from mit_core.spec import Instruction, ExtraInstruction, MitErrorCode
from mit_core.code_util import Code, copyright_banner, enum_to_c


GENERATOR_PROGRAM = 'gen-opcodes'
PURPOSE = 'Instruction opcodes.'
COPYRIGHT_YEARS = '2018-2019'


max_instruction = max([i.opcode for i in Instruction])
code = copyright_banner(GENERATOR_PROGRAM, PURPOSE, COPYRIGHT_YEARS)
code.append(f'''
#ifndef MIT_OPCODES
#define MIT_OPCODES


#define MIT_NUM_OPCODES {max_instruction + 1}

''')
code.append('')
code.extend(enum_to_c(Instruction, lambda i: i.opcode))
code.append('')
code.extend(enum_to_c(ExtraInstruction, lambda i: i.opcode))
code.append('')
code.extend(enum_to_c(MitErrorCode))
code.append('')
code.append('#endif')

print(code)
