#!/usr/bin/env python3
# Generate register list.
#
# (c) Mit authors 2019-2020
#
# The package is distributed under the MIT/X11 License.
#
# THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
# RISK.

from code_util import Code, copyright_banner, unrestrict
from spec import Registers


GENERATOR_PROGRAM = 'gen-registers'
PURPOSE = 'Register list.'
COPYRIGHT_YEARS = '1994-2020'

code = copyright_banner(GENERATOR_PROGRAM, PURPOSE, COPYRIGHT_YEARS)
code.append('')
for r in Registers:
    code.append(f"R({r.name}, {r.type}, {unrestrict(r.type)})")
print(code)
