#!/usr/bin/env python3

from instructions import Opcodes, actions

print('// Auto-generated by "gen-actions.py" - DO NOT EDIT.\n')

for (instruction, opcode) in Opcodes.__members__.items():
    print('''\
    case O_%(instruction)s:
        {
%(body)s
        }
        break;
''' % {
        'instruction': instruction,
        'body': actions[opcode][:-1].replace('\n', '\n            ')[1:],
    })
