#!/usr/bin/env python3
# Generate register list.
#
# (c) Mit authors 2019
#
# The package is distributed under the MIT/X11 License.
#
# THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
# RISK.

from mit_core.code_util import Code, copyright_banner, unrestrict
from mit_core.vm_data import Register


GENERATOR_PROGRAM = 'gen-registers'
PURPOSE = 'Register list.'
COPYRIGHT_YEARS = '1994-2019'

code = copyright_banner(GENERATOR_PROGRAM, PURPOSE, COPYRIGHT_YEARS)
code.append('')
for register in Register:
    code.append("{}({}, {}, {})".format(
        'R_RO' if register.read_only else 'R',
        register.name, register.type, unrestrict(register.type)))
print(code)
