#!/usr/bin/env python3
# Generate code for extra instructions.
#
# (c) Reuben Thomas 1994-2019
#
# The package is distributed under the MIT/X11 License.
#
# THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
# RISK.

from smite_core.vm_data_extra import *
from smite_core.instruction_gen import *

# Write the output file
print(includes)

print('''
#define RAISE(code)                         \
    return (code);                          \

// Assumption for file functions
verify(sizeof(int) <= sizeof(smite_WORD));
''')

for lib in LibActions:
    print('''\
static int extra_{}(smite_state *S, smite_WORD I)
{{
    smite_WORD temp;
'''.format(str.lower(lib.name)))
    print(dispatch(lib.value.library, '{}_'.format(lib.name), '            RAISE(15);'))
    print('''
    return 0;
}
''')

print('''
int smite_extra(smite_state *S, smite_WORD I)
{
    smite_WORD temp;
''')

print(dispatch(LibActions, '', '''
            return 1;'''))

print('''
    return 0;
}''')
