// List of VM register names.
//
// (c) Reuben Thomas 2018
//
// The package is distributed under the GNU Public License version 3, or,
// at your option, any later version.
//
// THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER‘S
// RISK.

R(BADPC, UWORD, UWORD)
R_RO(ENDISM, UWORD, UWORD)
R(HANDLER, UWORD, UWORD)
R(I, WORD, UWORD)
R(INVALID, UWORD, UWORD)
R(ITYPE, WORD, UWORD)
R_RO(MEMORY, UWORD, UWORD)
R(PC, UWORD, UWORD)
R(R0, UWORD, UWORD)
R(RP, UWORD, UWORD)
R_RO(RSIZE, UWORD, UWORD)
R(S0, WORDP, WORDP)
R(SP, WORDP, WORDP)
R_RO(SSIZE, UWORD, UWORD)